### ISSUE TITLE
System.ArgumentOutOfRangeException when UTC offset is positive.

### ISSUE THREAD

**Issue by donvreug** [paiden/Nett#25] opened 2017-05-06 22:55 UTC
When the computer's timezone is set to a positive offset, i.e. UTC+08:00, the following exception occurs when reading the toml file.  It reads ok when the system time zone is UTC or has a negative offset.

System.ArgumentOutOfRangeException occurred
  HResult=0x80131502
  Message=The UTC time represented when the offset is applied must be between year 0 and 10,000.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

**Comment by paiden** [comment] 2017-05-07 06:44
What is the contents of the TOML file?

**Comment by donvreug** [comment] 2017-05-07 21:25
Property4 = 2017-05-05T23:00:00+00:00

I have also tried just

Property4 = 2017-05-05

**Comment by paiden** [comment] 2017-05-08 05:46
It seems the problem is not directly caused by reading the TOML file. Adding a unit test and running it on my machine when the timezone is set to UTC+8 works without issues.

Maybe it is a Nett.Coma issue.

Could you provide the stack trace of  the exception and/or the code for a test that causes the exception?

**Comment by donvreug** [comment] 2017-05-08 08:40
StackTrace	"   at System.DateTimeOffset.ValidateDate(DateTime dateTime, TimeSpan offset)\r\n   at System.DateTimeOffset..ctor(DateTime dateTime)\r\n   at Nett.TomlConfig.<>c.<.cctor>b__34_28(ITomlRoot m, DateTime c) in D:\\Visual Studio\\Test\\TOML\\Source\\Nett\\TomlConfig.Builder.Conversion.cs:line 137\r\n   at Nett.TomlConverter`2.Convert(ITomlRoot root, TFrom from, Type targetType) in D:\\Visual Studio\\Test\\TOML\\Source\\Nett\\TomlConverter.cs:line 16\r\n   at Nett.TomlConverterBase`2.Convert(ITomlRoot root, Object o, Type targetType) in D:\\Visual Studio\\Test\\TOML\\Source\\Nett\\TomlConverterBase.cs:line 19\r\n   at Nett.TomlObject.CreateFrom(ITomlRoot root, Object val, PropertyInfo pi) in D:\\Visual Studio\\Test\\TOML\\Source\\Nett\\TomlObject.cs:line 55\r\n   at Nett.TomlTable.CreateFromClass[T](ITomlRoot root, T obj, TableTypes tableType) in D:\\Visual Studio\\Test\\TOML\\Source\\Nett\\TomlTable.cs:line 211\r\n   at Nett.TomlTable.From[T](TomlConfig config, T obj) in D:\\Visual Studio\\Test\\TOML\\Source\\Nett\\TomlTable.RootTable.cs:line 27\r\n   at Nett.Coma.Config.Create[T](Func`1 createDefault, IConfigSource source) in D:\\Visual Studio\\Test\\TOML\\Source\\Nett.Coma\\Config.cs:line 38\r\n   at TOMLSettings.CustomSettings.GetWorkingConfig() in D:\\Visual Studio\\Test\\AppSettingsTest\\TOMLSettings\\CustomSettings.cs:line 51\r\n   at TOMLSettings.ThisAddIn.ThisAddIn_Startup(Object sender, EventArgs e) in D:\\Visual Studio\\Test\\AppSettingsTest\\TOMLSettings\\ThisAddIn.cs:line 19\r\n   at Microsoft.Office.Tools.AddInImpl.OnStartup()\r\n   at TOMLSettings.ThisAddIn.FinishInitialization() in D:\\Visual Studio\\Test\\AppSettingsTest\\TOMLSettings\\ThisAddIn.Designer.cs:line 59\r\n   at Microsoft.VisualStudio.Tools.Office.Runtime.DomainCreator.ExecuteCustomization.ExecutePhase(ExecutionPhases executionPhases)\r\n   at Microsoft.VisualStudio.Tools.Office.Runtime.DomainCreator.ExecuteCustomization.Microsoft.VisualStudio.Tools.Office.Runtime.Interop.IExecuteCustomization2.ExecuteEntryPoints()"	string

**Comment by donvreug** [comment] 2017-05-08 09:17
Ok, The work around works.  Thanks.

**Comment by paiden** [comment] 2019-05-30 07:42
Fixed in 0.12.0

**Closed by paiden** 2019-05-30 07:42 UTC
Labels: bug, pending release
